
### if you want to use Prophet the api and point look at api.http from : https://github.com/novoytalo/forecastprophetdocker

###
POST http://localhost:3000/cats

###
GET http://localhost:3000/cats/docs
###
GET http://localhost:3000/cats/12
###
# the subdomain need to be configured over Docker host path
# GET http://account.exemple.com/3000

###
GET http://localhost:3000/cats/asyncfunction
#Get a async function on serve side
###
GET http://localhost:3000/cats/createdto


#in this case create a cat list... but it's only temp data,

###
POST http://localhost:3000/cats/usingprovider
Content-Type: application/json

{
    "name":"mycat1",
    "age":10,
    "breed":"unknow"
}
###
GET http://localhost:3000/cats/usingprovider

# using server to save data 
###
POST http://localhost:3000/users/usingprovider
Content-Type: application/json

{
    "id":"55",
    "name":"myUser22",
    "email":"test25@teste.com",
    "role":"admin",
    "status":true
}

###
GET http://localhost:3000/users/usingprovider

###
DELETE http://localhost:3000/users/usingprovider 
Content-Type: application/json

{
    "id":"4"
}

###
PATCH  http://localhost:3000/users/usingprovider
# 01/03/14
###
Get http://localhost:4000
//// great table

//table data organized by data internalcode
###
GET http://localhost:3000/grandetabela


# ###
# GET http://localhost:3000/grandetabela/interval_id

//data sorted by id and get one specific interval of ids 
# http://localhost:3000/grandetabela/`${interval_id_start}`/`${interval_id_end}`
###
GET http://localhost:3000/grandetabela/interval_id/0/100

###
GET http://host.docker.internal:3000/grandetabela/interval_id/0/100

###
POST http://localhost:3000/grandetabela/interval_date
Content-Type: application/json

{
    "interval_date_start": "2014-10-10T13:27:26.306Z" ,
    "interval_date_end": "2015-10-10T13:27:26.306Z"
}