version: '3.1'

services:
  db:
    image: postgres
    restart: always
    container_name: 'pgsql'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: pgpalavra
      POSTGRES_DB: mydatabase
    volumes:
      - pg-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  node-ytalo-backend:
    depends_on:
      - db
    build:
      context: .
      dockerfile: DockerFile.dev
    ports:
      - "3000:3000"
    command: >
      sh -c "npm install \
             npm run start:dev"
    environment:
          POSTGRES_USER: pgadmin
          POSTGRES_PASSWORD: pgpalavra
          POSTGRES_DB: mydatabase
          POSTGRES_HOST: db
    # or creat a .env and use env_file as rote
    # env_file:
    #   - .env
    restart: always
    volumes:
      - .:/home/node/appback
volumes:
  pg-data: