# use terminal command :
# docker-compose -f 'docker-compose-prod.yml' up --build
# docker-compose -f 'docker-compose-prod.yml' down
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    container_name: 'pgsql'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: pgpalavra
      POSTGRES_DB: mydatabase
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  node-ytalo-backend:
    image: ytalojacs/nestjsbasic_1-0
    ports:
      - "3000:3000"
    command: >
      sh -c "npm run build \
              npm run start:prod"
    environment:
          POSTGRES_USER: pgadmin
          POSTGRES_PASSWORD: pgpalavra
          POSTGRES_DB: mydatabase
          POSTGRES_HOST: db