# Use postgres/example user/password credentials
version: '3.1'

services:
  node-ytalo-backend:
    build:
      context: .
      dockerfile: DockerFile.dev
    ports:
      - "3000:3000"
    command: >
      sh -c "npm install \
             npm run start:dev"
    restart: always
    volumes:
      - .:/home/node/appback

  db:
    image: postgres
    restart: always
    container_name: 'pgsql'
    ports:
      - 8082:8082
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: pgpalavra
      POSTGRES_DB: meubandodedados
    

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080